/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
function load()
{
    dashcode.setupParts();
	loadPrefs();
	versionCheck();
}

//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{
    // Stop any timers to prevent CPU usage
    // Remove any preferences as needed
    // widget.setPreferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
	erasePrefs();
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{
    // Stop any timers to prevent CPU usage
	savePrefs();
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{
    // Restart any timers that were stopped on hide
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{
    // Retrieve any preference values that you need to be synchronized here
    // Use this for an instance key's value:
    // instancePreferenceValue = widget.preferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
    //
    // Or this for global key's value:
    // globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

//
// Function: showBack(event)
// Called when the info button is clicked to show the back of the widget
//
// event: onClick event from the info button
//
function showBack(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToBack");
    }

    front.style.display = "none";
    back.style.display = "block";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

//
// Function: showFront(event)
// Called when the done button is clicked from the back of the widget
//
// event: onClick event from the done button
//
function showFront(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToFront");
		updatePrefs();
    }

    front.style.display="block";
    back.style.display="none";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

if (window.widget) {
    widget.onremove = remove;
    widget.onhide = hide;
    widget.onshow = show;
    widget.onsync = sync;
}

// Begin app-specific functions

var PrestonBlair = "AI,E,FV,L,MBP,O,U,WQ,etc,rest";
var Flash = "1,2,3,4,5,6,7";

var wid = widget.identifier;
var prefFPS = loadPref(wid+"fps",30);
var prefKeyframe = loadPref(wid+"keyframe",0);
var prefPhoneme = loadPref(wid+"phoneme",0);
var prefPhonemeString = loadPref(wid+"phonemeString",PrestonBlair);
var prefPreset1 = loadPref(wid+"preset1","AI,E,FV,L,MBP,O,U,WQ,CHG,closed");
var prefPreset2 = loadPref(wid+"preset2","1,2,3,4,5,6,7,8,9,rest");

// Preference Saving

function loadPref(key,value) {
	var string = widget.preferenceForKey(key);
	if (string != null) {
		return string;
	} else {
		widget.setPreferenceForKey(value,key);
		return value;
	}
}

function loadPrefs() {
//	alert("ready!");
	document.getElementById("fps").value = prefFPS;
	document.getElementById("keyframe").object.setSelectedIndex(prefKeyframe);
	document.getElementById("phoneme").object.setSelectedIndex(prefPhoneme);
	document.getElementById("preset1").value = prefPreset1;
	document.getElementById("preset2").value = prefPreset2;
	updateFPS(fps);
}

function savePref(key,value) {
	if (window.widget) {
		widget.setPreferenceForKey(value,wid+key);
	}
}

function updatePrefs() {
	if (window.widget) {
		widget.setPreferenceForKey(prefFPS,wid+"fps");
		widget.setPreferenceForKey(prefKeyframe,wid+"keyframe");
		widget.setPreferenceForKey(prefPhoneme,wid+"phoneme");
		widget.setPreferenceForKey(prefPhoneme,wid+"phonemeString");
		widget.setPreferenceForKey(prefPreset1,wid+"preset1");
		widget.setPreferenceForKey(prefPreset2,wid+"preset2");
	}
}

function erasePrefs() {
	if (window.widget) {
		widget.setPreferenceForKey(null,wid+"fps");
		widget.setPreferenceForKey(null,wid+"keyframe");
		widget.setPreferenceForKey(null,wid+"phoneme");
		widget.setPreferenceForKey(null,wid+"phonemeString");
		widget.setPreferenceForKey(null,wid+"preset1");
		widget.setPreferenceForKey(null,wid+"preset2");
	}
}

// Basic Functions

function updateFPS(event) {
	var fps = document.getElementById("fps");
	prefFPS = parseInt(fps.value);
//	fps.value = prefFPS+"fps";

	if (event.type == "keyup") {
		if (event.keyCode == "13" || event.keyCode == "38" || event.keyCode == "40") {
			fps.value = prefFPS+"fps";
			selectIt(fps);
		}
	} else {
		fps.value = prefFPS+"fps";
	}
	updatePrefs();
}

function updateKeyframe(event) {
	prefKeyframe = document.getElementById("keyframe").object.getSelectedIndex();
	updatePrefs();
}

function updatePhoneme(event) {
	prefPhoneme = document.getElementById("phoneme").object.getSelectedIndex();
//	alert("prefPhoneme = "+prefPhoneme);
	if (prefPhoneme > 1) {
		var preset = "preset"+(prefPhoneme-1);
		prefPhonemeString = document.getElementById(preset).value;
//		alert("prefPhonemeString = "+prefPhonemeString);
	} else if (prefPhoneme == 1) {
		prefPhonemeString = Flash;
//		alert("prefPhonemeString = "+prefPhonemeString);
	} else {
		prefPhonemeString = PrestonBlair;
//		alert("prefPhonemeString = "+prefPhonemeString);
	}
	updatePrefs();
}

function updatePreset(event) {
//	var fps = document.getElementById("fps");
//	prefKeyframe = parseFloat(fps.value);
}

// Be sure to assign these handlers for the ondragenter and ondragover events on your drop target. These handlers prevent Web Kit from processing drag events so you can handle the drop when it occurs.

function dragEnter(event) {
	event.stopPropagation();
	event.preventDefault();
}

function dragOver(event) {
	event.stopPropagation();
	event.preventDefault();
}

function dragDrop(event) {
	try {
		uri = event.dataTransfer.getData("text/uri-list");
alert("uri = "+uri);
		uri = uri.replace(/file:\/\/localhost/g, "");
		uri = uri.replace(/\%20/g, "\\ ");
//		uri = uri.replace(/\n/g, " ");

		if (uri.match("\n")) {
			showFail();
//			uri = uri.split("\n");
//			for(var i in uri) {
//				alert("uri[i] = "+uri[i]);
//				if (uri[i].length>2) widget.system("cat "+uri[i], processInput).outputString;
//			}
		} else {
			alert("uri = "+uri);
			widget.system("cat "+uri, processInput).outputString;
		}
	} catch (ex) {
		alert("Problem fetching URI: " + ex);
		showFail(event);
	}

	event.stopPropagation();
	event.preventDefault();
}

function processInput(event) {
	input = event.outputString;
	if (!input) return showEmpty();
	input = input.replace(/\r\n|\n|\r/gi," ");

	if (input.search(/MohoSwitch/i)<0) {
		return showWrong(event);
	}
//	alert("Raw Input = "+event.outputString);
//	alert("Processed Input = "+input);

	var string = prefPhonemeString.split(',');
	var keytype = document.getElementById("keyframe").object.getValue();
	var keydex = document.getElementById("keyframe").object.getSelectedIndex();

	if (keydex >= 4) {
		keyframeAE(string,keytype)
	} else {
		for(var i in string) {
//			alert(string[i]);
			keyframeLW(string[i],keytype);
		}
	}
}

function keyframeLW(phoneme,keytype) {
	var a1 = input.split(" ");
	var len = a1.length-1;
	var len2 = Math.round((len/2)-0.25);
	var output = "  " + len2 + "\n";
	for (i=0;i<len;i++){
		if (i%2==1){
		var a2 = a1[i+1];
			if (a2 == phoneme) {
			var keyvalue = "1";
			} else {
			var keyvalue = "0";
			}
		output = output + "  Key " + keyvalue + " " + (a1[i]/prefFPS) + keytype + " 0 0 0 0 0\n";
		}
	}

	var myCommand = widget.system("cat > "+uri+"."+phoneme+".env", endHandler);
	myCommand.write("{ Envelope\n"+output+"  Behaviors 1 1\n}");
	myCommand.close();

	return	showSuccess();
}

function keyframeAE(phonemes,keytype) {
	var a1 = input.split(" ");
	var len = a1.length-1;
	var len2 = Math.round((len/2)-0.25);
	var output = "Adobe After Effects 8.0 Keyframe Data";
	alert("prefFPS = "+prefFPS);
	var output = output+"\r\n\r\n\tUnits Per Second\t"+prefFPS;
	var output = output+"\r\n\tSource Width\t720";
	var output = output+"\r\n\tSource Height\t720";
	var output = output+"\r\n\tSource Pixel Aspect Ratio\t1";
	var output = output+"\r\n\tComp Pixel Aspect Ratio\t1";

	var output = output+"\r\n\r\nTime Remap\r\n\tFrame\tseconds\t\r\n";
	var keytypeNum = "1";
	if (keytype == "frames") {
		keytypeNum = prefFPS;
	}

	for (i=0;i<len;i++){
		if (i%2==1){
			var a2 = a1[i+1];
			var keyvalue = phonemes.indexOf(a2);
			output = output+"\t"+(a1[i]-1)+"\t"+(keyvalue/keytypeNum).toFixed(6)+"\t\r\n";
		}
	}

	output = output+"\r\n\r\nEnd of Keyframe Data\r\n";

	var myCommand = widget.system("cat > "+uri+".AE"+keytype+".txt", endHandler);
	myCommand.write(output);
	myCommand.close();
//	widget.system("open "+uri+".AE"+keytype+".txt");
	copy(output);

	document.getElementById("successTextAEoutput").innerHTML = "sequential phoneme list: "+phonemes.join(", ");
	return	showSuccessAE();
}

function endHandler(event) {
	return setTimeout("showMain()",4000);
//	return showMain();
}

// Clipboard

function copy(value){
    widget.system("/usr/bin/osascript -e 'set the clipboard to \"" + value + "\"'", null);
}

// Key listeners

function keyboard(event) {
	var data = parseFloat(event.target.value);
	if (event.keyCode == 38) {
		if (event.shiftKey == true) {
			event.target.value = data+10
		} else {
			event.target.value = data+1
		}
		return true;
	} else if (event.keyCode == 40) {
		if (event.shiftKey == true) {
			event.target.value = data-10
		} else {
			event.target.value = data-1
		}
		return true;
	} else {
		return true;
	}
}

function selectIt(event) {
	if(event.target){
		event = event.target
	}
//	event.focus();
	event.select();
}

// CurrentView animations

function showMain(event) {
	document.getElementById("stack").object.setCurrentView("main", false, true);
}

function showSuccess(event) {
	document.getElementById("stack").object.setCurrentView("success", true, true);
}

function showSuccessAE(event) {
	document.getElementById("stack").object.setCurrentView("successAE", true, true);
}

function showEmpty(event) {
	document.getElementById("stack").object.setCurrentView("empty", true, true);
}

function showFail(event) {
	document.getElementById("stack").object.setCurrentView("fail", true, true);
}

function showWrong(event) {
	document.getElementById("stack").object.setCurrentView("wrong", true, true);
}

function showUpdate(event) {
	document.getElementById("stack").object.setCurrentView("update", true, true);
}

// Get Key Value

function getKeyValue(plist, key) {
	var infoPlist = new XMLHttpRequest();
	infoPlist.open("GET", plist, false);
	infoPlist.send(null);
	infoPlist = infoPlist.responseText.replace(/(<([^>]+)>)/ig,"").replace(/\t/ig,"").split("\n");
	for (var i=0; i<infoPlist.length; i++)
		if (infoPlist[i] == key) return infoPlist[i+1];
	return false;
}

// Auto Update

function versionCheck(event) {
	var request = new XMLHttpRequest();
	var address = "http://iaian7.com/files/dashboard/lipsync/version.php?RandomKey=" + Date.parse(new Date());
	alert(address);
	request.open("GET", address,false);
	request.send(null);
	var versions = request.responseText.split("\n");

	var bundleVersion = getKeyValue("Info.plist", "CFBundleVersion"); 
	var websiteVersion = versions[0];
	alert("bundleVersion: "+bundleVersion);
	alert("websiteVersion: "+websiteVersion);

	if (websiteVersion != bundleVersion) {
		document.getElementById("newVersion").innerHTML = "version "+versions[0]+"<br/>"+versions[1];
		showUpdate();
	} else {
		alert("you have an up to date version, or there's been an error");
	}
}

// Download File

function versionDownload() {
	widget.openURL("http://iaian7.com/files/dashboard/lipsync/LipSync.zip");
	showMain();
}

// Visit the website

function iaian7(event)
{
	widget.openURL("http://iaian7.com/dashboard/lipsync");
}