/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "doneSave": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showFront", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "download": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "versionDownload", "rightImageWidth": 5, "text": "download", "view": "DC.View" },
    "drop": { "text": "drop", "view": "DC.Text" },
    "emptyText": { "text": "empty", "view": "DC.Text" },
    "explanation": { "text": "explanation", "view": "DC.Text" },
    "failButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "failButton1": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "failText": { "text": "fail", "view": "DC.Text" },
    "iaian7com": { "text": "iaian7com", "view": "DC.Text" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack", "view": "DC.View" },
    "keyframe": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "onchange": "updateKeyframe", "options": [["LW linear", " 3 0"], ["LW stepped", " 4 0"], ["LW TCB", " 0 0"], ["LW TCB flat", " 0 1"], ["AE frames", "frames"], ["AE seconds", "seconds"]], "rightImageWidth": 16, "view": "DC.View" },
    "new": { "text": "new", "view": "DC.Text" },
    "newVersion": { "text": "newVersion", "view": "DC.Text" },
    "phoneme": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "onchange": "updatePhoneme", "options": [["preston blair", "0"], ["simplified flash", "1"], ["user preset 1", "2"], ["user preset 2", "3"]], "rightImageWidth": 16, "view": "DC.View" },
    "preset1text": { "text": "preset1", "view": "DC.Text" },
    "preset2text": { "text": "preset2", "view": "DC.Text" },
    "skip": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "skip", "view": "DC.View" },
    "stack": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "successButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "successButtonAE": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "successText": { "text": "success", "view": "DC.Text" },
    "successText2": { "text": "success2", "view": "DC.Text" },
    "successTextAE": { "text": "successAE", "view": "DC.Text" },
    "successTextAE2": { "text": "successAE2", "view": "DC.Text" },
    "successTextAEoutput": { "text": "successAEoutput", "view": "DC.Text" },
    "text": { "text": "©2009 John Einselen / Vectorform LLC", "view": "DC.Text" },
    "wrongButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "wrongText": { "text": "wrong", "view": "DC.Text" }
};

