/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "doneSave": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showFront", "rightImageWidth": 5, "text": "done" },
    "download": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "versionDownload", "rightImageWidth": 5, "text": "download" },
    "drop": { "creationFunction": "CreateText", "text": "drop" },
    "emptyText": { "creationFunction": "CreateText", "text": "empty" },
    "explanation": { "creationFunction": "CreateText", "text": "explanation" },
    "failButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "failButton1": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "failText": { "creationFunction": "CreateText", "text": "fail" },
    "iaian7com": { "creationFunction": "CreateText", "text": "iaian7com" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "keyframe": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "onchange": "updateKeyframe", "options": [["LW linear", " 3 0"], ["LW stepped", " 4 0"], ["LW TCB", " 0 0"], ["LW TCB flat", " 0 1"], ["AE frames", "frames"], ["AE seconds", "seconds"]], "rightImageWidth": 16 },
    "new": { "creationFunction": "CreateText", "text": "new" },
    "newVersion": { "creationFunction": "CreateText", "text": "newVersion" },
    "phoneme": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "onchange": "updatePhoneme", "options": [["preston blair", "0"], ["simplified flash", "1"], ["user preset 1", "2"], ["user preset 2", "3"]], "rightImageWidth": 16 },
    "preset1text": { "creationFunction": "CreateText", "text": "preset1" },
    "preset2text": { "creationFunction": "CreateText", "text": "preset2" },
    "skip": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "skip" },
    "stack": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }] },
    "successButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "successButtonAE": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "successText": { "creationFunction": "CreateText", "text": "success" },
    "successText2": { "creationFunction": "CreateText", "text": "success2" },
    "successTextAE": { "creationFunction": "CreateText", "text": "successAE" },
    "successTextAE2": { "creationFunction": "CreateText", "text": "successAE2" },
    "successTextAEoutput": { "creationFunction": "CreateText", "text": "successAEoutput" },
    "text": { "creationFunction": "CreateText", "text": "©2009 John Einselen / Vectorform LLC" },
    "wrongButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "wrongText": { "creationFunction": "CreateText", "text": "wrong" }
};
