/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "done": "done",
    "download": "download",
    "drop": "drop MOHO file here",
    "empty": "file was empty\nplease try again",
    "explanation": "Custom phoneme lists should be comma delimited and contain no spaces.",
    "fail": "file processing failed\nplease try again",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/lipsync",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "preset1": "user preset 1",
    "preset2": "user preset 2",
    "skip": "skip version",
    "success": "file conversion\nwas successful",
    "success2": "(envelope files saved)",
    "successAE": "file conversion\nwas successful\n(and copied to clipboard)",
    "successAE2": "sequential phoneme list:",
    "successAEoutput": "sequential phoneme list",
    "wrong": "wrong file format\nplease try again"
};

